#arithemtic operators
a = int(input("Enter the value of a:"))
b = int(input("Enter the value of b:"))
print('a + b = ', a + b)
print('a - b = ', a - b)
print('a * b = ', a * b)
print('a / b = ', a / b)
print('a // b = ', a // b)
print('a % b = ', a % b)
print('a ** b = ', a ** b)
print('a ** 0.5 = ', a ** 0.5)
